(global-set-key (kbd "C-c f") 'windmove-right)
(global-set-key (kbd "C-c b") 'windmove-left)
(global-set-key (kbd "C-c p") 'windmove-up)
(global-set-key (kbd "C-c n") 'windmove-down)
(global-set-key (kbd "C-c q") 'delete-window)
(global-set-key (kbd "C-c v") 'split-window-right)
(global-set-key (kbd "C-c h") 'split-window-below)
