#!/bin/bash

SESSION=reverb
cd $HOME/dev/$SESSION
tmux new -s $SESSION -d

tmux send-keys -t $SESSION './dev/docker/up db core-redis' C-m
until dev/docker/exec db psql -U postgres -h localhost -c "select 1" > /dev/null 2>&1; do sleep 2; done
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION 'zeus start' C-m

tmux select-window -t $SESSION:1
tmux attach -t $SESSION
