#!/bin/bash

SESSION=reverb
cd $HOME/dev/$SESSION
tmux new -s $SESSION -d
tmux send-keys -t $SESSION 'vagrant up; tmux wait-for -S getting-to-work' C-m\; wait-for getting-to-work
tmux rename-window -t $SESSION vim
tmux send-keys -t $SESSION 'vim' C-m
tmux split-window -v -t $SESSION

tmux new-window -t $SESSION
tmux rename-window -t $SESSION other
tmux send-keys -t $SESSION './script/server' C-m
tmux split-window -v -t $SESSION
tmux send-keys -t $SESSION 'zeus start' C-m
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION 'npm run dev' C-m
tmux select-pane -t $SESSION -U
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION 'vagrant ssh -c "service worker stop && exit"; ./bin/sidekiq' C-m

tmux select-window -t $SESSION:1
tmux attach -t $SESSION
