#!/bin/bash

SESSION=reverb
cd $HOME/dev/$SESSION
tmux new -s $SESSION -d
tmux rename-window -t $SESSION vim
tmux send-keys -t $SESSION 'vim' C-m
tmux split-window -v -t $SESSION

tmux new-window -t $SESSION
tmux rename-window -t $SESSION other
tmux split-window -v -t $SESSION
tmux send-keys -t $SESSION './dev/up' C-m
until dev/exec db psql -U postgres -h localhost -c "select 1" > /dev/null 2>&1; do sleep 2; done
tmux split-window -v -t $SESSION
tmux send-keys -t $SESSION 'npm run dev' C-m
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION './bin/sidekiq > /dev/null 2>&1' C-m
tmux select-pane -t $SESSION -U
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION 'nginx -c nginx.dev.conf -p ./' C-m
tmux select-pane -t $SESSION -U
tmux send-keys -t $SESSION './bin/rails s -b 127.0.0.1' C-m
tmux split-window -h -t $SESSION
tmux send-keys -t $SESSION 'zeus start' C-m

tmux select-window -t $SESSION:1
tmux attach -t $SESSION
