#!/bin/bash

SESSION=blog

tmux new-session -d -s $SESSION

cd ~/programs/peterdebelak
tmux split-window -v
tmux resize-pane -D 10
tmux select-pane -t 1
tmux send-keys "vim" C-m
tmux new-window -t $SESSION:2
cd ~/programs/peterdebelak
tmux send-keys "bundle exec jekyll serve -- drafts" C-m
tmux select-window -t $SESSION:1

tmux attach-session -t $SESSION
